# Generated by Django 4.1.4 on 2022-12-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealclick',
            name='user_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
